/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-25 at 01:51:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.numeralpursuit.gameserver.model;

/**
 * Model definition for FriendData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gameserver. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FriendData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String friendEmail;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long friendId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String friendNick;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFriendEmail() {
    return friendEmail;
  }

  /**
   * @param friendEmail friendEmail or {@code null} for none
   */
  public FriendData setFriendEmail(java.lang.String friendEmail) {
    this.friendEmail = friendEmail;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFriendId() {
    return friendId;
  }

  /**
   * @param friendId friendId or {@code null} for none
   */
  public FriendData setFriendId(java.lang.Long friendId) {
    this.friendId = friendId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFriendNick() {
    return friendNick;
  }

  /**
   * @param friendNick friendNick or {@code null} for none
   */
  public FriendData setFriendNick(java.lang.String friendNick) {
    this.friendNick = friendNick;
    return this;
  }

  @Override
  public FriendData set(String fieldName, Object value) {
    return (FriendData) super.set(fieldName, value);
  }

  @Override
  public FriendData clone() {
    return (FriendData) super.clone();
  }

}
