/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-25 at 01:51:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.numeralpursuit.gameserver.model;

/**
 * Model definition for FriendlyGameData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gameserver. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FriendlyGameData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id2;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId1() {
    return id1;
  }

  /**
   * @param id1 id1 or {@code null} for none
   */
  public FriendlyGameData setId1(java.lang.Long id1) {
    this.id1 = id1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId2() {
    return id2;
  }

  /**
   * @param id2 id2 or {@code null} for none
   */
  public FriendlyGameData setId2(java.lang.Long id2) {
    this.id2 = id2;
    return this;
  }

  @Override
  public FriendlyGameData set(String fieldName, Object value) {
    return (FriendlyGameData) super.set(fieldName, value);
  }

  @Override
  public FriendlyGameData clone() {
    return (FriendlyGameData) super.clone();
  }

}
