/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-25 at 01:51:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.numeralpursuit.gameserver.model;

/**
 * Model definition for GameInfo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gameserver. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GameInfo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gameId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gameName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer gameType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long opId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String opNames;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer reasonEnded;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer result;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGameId() {
    return gameId;
  }

  /**
   * @param gameId gameId or {@code null} for none
   */
  public GameInfo setGameId(java.lang.Long gameId) {
    this.gameId = gameId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getGameName() {
    return gameName;
  }

  /**
   * @param gameName gameName or {@code null} for none
   */
  public GameInfo setGameName(java.lang.String gameName) {
    this.gameName = gameName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getGameType() {
    return gameType;
  }

  /**
   * @param gameType gameType or {@code null} for none
   */
  public GameInfo setGameType(java.lang.Integer gameType) {
    this.gameType = gameType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOpId() {
    return opId;
  }

  /**
   * @param opId opId or {@code null} for none
   */
  public GameInfo setOpId(java.lang.Long opId) {
    this.opId = opId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getOpNames() {
    return opNames;
  }

  /**
   * @param opNames opNames or {@code null} for none
   */
  public GameInfo setOpNames(java.lang.String opNames) {
    this.opNames = opNames;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getReasonEnded() {
    return reasonEnded;
  }

  /**
   * @param reasonEnded reasonEnded or {@code null} for none
   */
  public GameInfo setReasonEnded(java.lang.Integer reasonEnded) {
    this.reasonEnded = reasonEnded;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResult() {
    return result;
  }

  /**
   * @param result result or {@code null} for none
   */
  public GameInfo setResult(java.lang.Integer result) {
    this.result = result;
    return this;
  }

  @Override
  public GameInfo set(String fieldName, Object value) {
    return (GameInfo) super.set(fieldName, value);
  }

  @Override
  public GameInfo clone() {
    return (GameInfo) super.clone();
  }

}
