/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-25 at 01:51:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.numeralpursuit.gameserver.model;

/**
 * Model definition for PlayerNicks.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gameserver. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PlayerNicks extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idOne;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idTwo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nickOne;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nickTwo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdOne() {
    return idOne;
  }

  /**
   * @param idOne idOne or {@code null} for none
   */
  public PlayerNicks setIdOne(java.lang.Long idOne) {
    this.idOne = idOne;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdTwo() {
    return idTwo;
  }

  /**
   * @param idTwo idTwo or {@code null} for none
   */
  public PlayerNicks setIdTwo(java.lang.Long idTwo) {
    this.idTwo = idTwo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNickOne() {
    return nickOne;
  }

  /**
   * @param nickOne nickOne or {@code null} for none
   */
  public PlayerNicks setNickOne(java.lang.String nickOne) {
    this.nickOne = nickOne;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNickTwo() {
    return nickTwo;
  }

  /**
   * @param nickTwo nickTwo or {@code null} for none
   */
  public PlayerNicks setNickTwo(java.lang.String nickTwo) {
    this.nickTwo = nickTwo;
    return this;
  }

  @Override
  public PlayerNicks set(String fieldName, Object value) {
    return (PlayerNicks) super.set(fieldName, value);
  }

  @Override
  public PlayerNicks clone() {
    return (PlayerNicks) super.clone();
  }

}
