/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-25 at 01:51:37 UTC 
 * Modify at your own risk.
 */

package com.appspot.numeralpursuit.gameserver.model;

/**
 * Model definition for Settings.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gameserver. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Settings extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean notifyFriendChatUpdates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean notifyGameChatUpdates;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean notifyGameRequest;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean notifyGameUpdate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float opacity;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public Settings setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getNotifyFriendChatUpdates() {
    return notifyFriendChatUpdates;
  }

  /**
   * @param notifyFriendChatUpdates notifyFriendChatUpdates or {@code null} for none
   */
  public Settings setNotifyFriendChatUpdates(java.lang.Boolean notifyFriendChatUpdates) {
    this.notifyFriendChatUpdates = notifyFriendChatUpdates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getNotifyGameChatUpdates() {
    return notifyGameChatUpdates;
  }

  /**
   * @param notifyGameChatUpdates notifyGameChatUpdates or {@code null} for none
   */
  public Settings setNotifyGameChatUpdates(java.lang.Boolean notifyGameChatUpdates) {
    this.notifyGameChatUpdates = notifyGameChatUpdates;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getNotifyGameRequest() {
    return notifyGameRequest;
  }

  /**
   * @param notifyGameRequest notifyGameRequest or {@code null} for none
   */
  public Settings setNotifyGameRequest(java.lang.Boolean notifyGameRequest) {
    this.notifyGameRequest = notifyGameRequest;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getNotifyGameUpdate() {
    return notifyGameUpdate;
  }

  /**
   * @param notifyGameUpdate notifyGameUpdate or {@code null} for none
   */
  public Settings setNotifyGameUpdate(java.lang.Boolean notifyGameUpdate) {
    this.notifyGameUpdate = notifyGameUpdate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Float getOpacity() {
    return opacity;
  }

  /**
   * @param opacity opacity or {@code null} for none
   */
  public Settings setOpacity(java.lang.Float opacity) {
    this.opacity = opacity;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public Settings setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public Settings set(String fieldName, Object value) {
    return (Settings) super.set(fieldName, value);
  }

  @Override
  public Settings clone() {
    return (Settings) super.clone();
  }

}
